# Generated by Django 3.2.22 on 2023-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call')], default='Email', max_length=20)),
                ('message', models.TextField(max_length=20)),
            ],
        ),
    ]
