# Generated by Django 3.2.22 on 2023-11-22 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBoardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('snow', 'Snowboard'), ('surf', 'Surfboard'), ('skate', 'Skateboard')], max_length=20)),
                ('board_class', models.CharField(choices=[('regular_skate', 'Regular Skate'), ('cruiser', 'Cruiser'), ('mini', 'Mini'), ('shortboard', 'Shortboard'), ('hybrid', 'Hybrid Board'), ('longboard', 'Longboard'), ('mens_snowboard', "Men's Snowboard"), ('womens_snowboard', "Women's Snowboard"), ('kids_snowboard', 'Kids Snowboard')], max_length=20)),
                ('board_length', models.IntegerField()),
                ('board_width', models.IntegerField()),
                ('board_thickness', models.IntegerField()),
                ('image_upload', models.ImageField(upload_to='custom_board_images/')),
                ('board_color', models.CharField(max_length=10)),
                ('additional_notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
